# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuClassification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "bu_classification_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("classification_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "bu_classifications",
                "ordering": ["classification_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BuLead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("bu_lead_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("employee_id_legacy", models.BigIntegerField(blank=True, null=True)),
                ("lead_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=320)),
            ],
            options={
                "db_table": "bu_leads",
                "ordering": ["lead_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeGrade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "employee_grade_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("grade_name", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "employee_grades",
                "ordering": ["grade_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "employee_group_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("group_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "employee_groups",
                "ordering": ["group_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("estate_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("estate_name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "estates",
                "ordering": ["estate_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Lob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("lob_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("lob_name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "LOB",
                "verbose_name_plural": "LOBs",
                "db_table": "lob",
                "ordering": ["lob_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("location_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("location_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["location_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("region_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("region_name", models.CharField(max_length=150, unique=True)),
                ("geography", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "regions",
                "ordering": ["region_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("center_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("center_name", models.CharField(max_length=150)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centers",
                        to="organization.location",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centers",
                        to="organization.region",
                    ),
                ),
            ],
            options={
                "db_table": "centers",
                "ordering": ["center_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("process_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("process_name", models.CharField(max_length=255)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="organization.location",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="organization.region",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "processes",
                "db_table": "processes",
                "ordering": ["process_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                db_column="region_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="organization.region",
            ),
        ),
        migrations.CreateModel(
            name="Subprocess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "subprocess_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("subprocess_name", models.CharField(max_length=255)),
                (
                    "process",
                    models.ForeignKey(
                        db_column="process_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subprocesses",
                        to="organization.process",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "subprocesses",
                "db_table": "subprocesses",
                "ordering": ["subprocess_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CostCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "cost_code_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("cost_code", models.CharField(db_index=True, max_length=80)),
                (
                    "bu_lead",
                    models.ForeignKey(
                        blank=True,
                        db_column="bu_lead_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.bulead",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        db_column="center_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.center",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        db_column="estate_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.estate",
                    ),
                ),
                (
                    "lob",
                    models.ForeignKey(
                        blank=True,
                        db_column="lob_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.lob",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.location",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        db_column="process_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.process",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.region",
                    ),
                ),
                (
                    "subprocess",
                    models.ForeignKey(
                        blank=True,
                        db_column="subprocess_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_codes",
                        to="organization.subprocess",
                    ),
                ),
            ],
            options={
                "db_table": "cost_codes",
                "ordering": ["cost_code"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(
                        fields=["estate", "active_flag", "cost_code"],
                        name="idx_cc_estate_active_code",
                    ),
                    models.Index(
                        fields=["estate", "process"], name="idx_cc_estate_process"
                    ),
                    models.Index(
                        fields=["estate", "bu_lead"], name="idx_cc_estate_bulead"
                    ),
                    models.Index(
                        fields=["estate", "subprocess"], name="idx_cc_estate_subproc"
                    ),
                    models.Index(
                        fields=["estate", "region"], name="idx_cc_estate_region"
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
