# Generated by Django 5.2.17 on 2026-09-13 08:42

import apps.accounts.models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("role_code", models.CharField(max_length=80, unique=True)),
                ("role_name", models.CharField(max_length=150)),
                ("active_flag", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("employee_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_row_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("employee_number", models.CharField(max_length=30, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=320)),
                ("designation", models.CharField(blank=True, max_length=150)),
                ("domain_name", models.CharField(blank=True, max_length=150)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("contact_number", models.CharField(blank=True, max_length=50)),
                ("employment_status", models.CharField(blank=True, max_length=50)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("last_working_date", models.DateField(blank=True, null=True)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bu_classification",
                    models.ForeignKey(
                        blank=True,
                        db_column="bu_classification_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.buclassification",
                    ),
                ),
                (
                    "bu_lead",
                    models.ForeignKey(
                        blank=True,
                        db_column="bu_lead_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.bulead",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        db_column="center_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.center",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="cost_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.costcode",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="current_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees_currently_at",
                        to="organization.location",
                    ),
                ),
                (
                    "employee_grade",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_grade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.employeegrade",
                    ),
                ),
                (
                    "employee_group",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_group_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.employeegroup",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        db_column="estate_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.estate",
                    ),
                ),
                (
                    "lob",
                    models.ForeignKey(
                        blank=True,
                        db_column="lob_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.lob",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.location",
                    ),
                ),
                (
                    "manager_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="manager_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="accounts.employee",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        db_column="process_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.process",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.region",
                    ),
                ),
                (
                    "subprocess",
                    models.ForeignKey(
                        blank=True,
                        db_column="subprocess_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.subprocess",
                    ),
                ),
                (
                    "supervisor_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="supervisor_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisees",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employees",
                "ordering": ["full_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(max_length=320, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Suspended", "Suspended"),
                            ("Disabled", "Disabled"),
                        ],
                        default="Active",
                        max_length=30,
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("google", "Google"),
                            ("microsoft", "Microsoft"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("provider_subject", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_account",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "db_table": "user_accounts",
                "ordering": ["display_name"],
            },
            managers=[
                ("objects", apps.accounts.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "otp_challenge_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN_2FA", "Login second factor"),
                            ("PASSWORD_RESET", "Password reset"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEstateScope",
            fields=[
                (
                    "user_estate_scope_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("active_flag", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estate",
                    models.ForeignKey(
                        db_column="estate_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scopes",
                        to="organization.estate",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="granted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estate_scopes_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_estate_scopes",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "user_role_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_roles",
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["cost_code"], name="idx_emp_cost_code"),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_subject", ""), _negated=True),
                fields=("auth_provider", "provider_subject"),
                name="uq_user_provider_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(
                fields=["user", "purpose", "consumed_at"], name="idx_otp_user_purpose"
            ),
        ),
        migrations.AddConstraint(
            model_name="userestatescope",
            constraint=models.UniqueConstraint(
                fields=("user", "estate"), name="uq_user_estate"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="uq_user_role"
            ),
        ),
    ]
