# Generated by Django 5.2.17 on 2026-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="mfa_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
