# Generated by Django 5.2.17 on 2026-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_mfa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="avatar_data_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="job_title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
