# Generated by Django 5.2.17 on 2026-09-14 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0003_phase9"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                ("report_request_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ESTATE_DETAIL", "Estate detail report"),
                            ("COORDINATOR_ASSIGNMENTS", "Coordinator assignment report"),
                            ("CALL_TREE_RUNS", "Call tree run report"),
                            ("EXEMPTION_REGISTER", "Exemption register"),
                            ("DASHBOARD_SUMMARY", "Dashboard summary"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("xlsx", "Excel"), ("csv", "CSV"), ("pdf", "PDF")],
                        default="xlsx",
                        max_length=10,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("ONCE", "Once"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="ONCE",
                        max_length=10,
                    ),
                ),
                ("active_flag", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_requests",
                        to="documents.document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        db_column="requested_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
