# Generated by Django 5.2.17 on 2026-09-14 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_phase9"),
        ("reporting", "0001_phase9"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reportrequest",
            index=models.Index(
                fields=["requested_by", "created_at"], name="idx_reports_user_created"
            ),
        ),
    ]
