# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organization", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallTreeRun",
            fields=[
                (
                    "call_tree_run_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("broadcast_id", models.CharField(blank=True, max_length=100)),
                ("call_tree_type", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("simulation_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        db_column="center_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_tree_runs",
                        to="organization.center",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="cost_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_tree_runs",
                        to="organization.costcode",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="plan_version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_tree_runs",
                        to="plans.planversion",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        db_column="process_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_tree_runs",
                        to="organization.process",
                    ),
                ),
            ],
            options={
                "db_table": "call_tree_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CallTreeMember",
            fields=[
                (
                    "call_tree_member_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("member_name", models.CharField(blank=True, max_length=200)),
                ("member_email", models.EmailField(blank=True, max_length=320)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("sequence_number", models.IntegerField(blank=True, null=True)),
                ("escalation_level", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_tree_memberships",
                        to="accounts.employee",
                    ),
                ),
                (
                    "call_tree_run",
                    models.ForeignKey(
                        db_column="call_tree_run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="calltree.calltreerun",
                    ),
                ),
            ],
            options={
                "db_table": "call_tree_members",
                "ordering": ["call_tree_run", "escalation_level", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="CallAttempt",
            fields=[
                (
                    "call_attempt_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("VOICE", "Voice"),
                            ("MS_TEAMS", "Microsoft Teams"),
                            ("EMAIL", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("attempt_status", models.CharField(blank=True, max_length=50)),
                ("status_code", models.CharField(blank=True, max_length=50)),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("response_key", models.CharField(blank=True, max_length=100)),
                ("call_duration_seconds", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "call_tree_member",
                    models.ForeignKey(
                        db_column="call_tree_member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="calltree.calltreemember",
                    ),
                ),
            ],
            options={
                "db_table": "call_attempts",
                "ordering": ["call_tree_member", "attempt_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("call_tree_member", "channel", "attempt_number"),
                        name="uq_call_attempt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("channel__in", ["VOICE", "MS_TEAMS", "EMAIL"])
                        ),
                        name="ck_call_channel",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="calltreemember",
            index=models.Index(fields=["call_tree_run"], name="idx_ctm_run"),
        ),
    ]
