# Generated by Django 5.2.17 on 2026-09-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calltree", "0001_initial"),
        ("crisis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callattempt",
            name="provider_reference",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="calltreemember",
            name="cmsc_member",
            field=models.ForeignKey(
                blank=True,
                db_column="cmsc_member_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_tree_memberships",
                to="crisis.cmscmember",
            ),
        ),
        migrations.AddField(
            model_name="calltreemember",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calltreemember",
            name="reached_channel",
            field=models.CharField(
                blank=True,
                choices=[("VOICE", "Voice"), ("MS_TEAMS", "Microsoft Teams"), ("EMAIL", "Email")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="calltreemember",
            name="reached_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calltreerun",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="initiated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_tree_runs_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calltreerun",
            name="providers_enabled",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="calltreerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
