# Generated by Django 5.2.17 on 2026-09-14 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calltree", "0002_phase8"),
        ("organization", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="calltreerun",
            index=models.Index(fields=["cost_code", "started_at"], name="idx_ctr_cc_started"),
        ),
        migrations.AddIndex(
            model_name="calltreerun",
            index=models.Index(fields=["status"], name="idx_ctr_status"),
        ),
    ]
