# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "audit_log_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login success"),
                            ("LOGIN_FAILURE", "Login failure"),
                            ("LOGIN_LOCKOUT", "Login lockout"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_RESET", "Password reset"),
                            ("ROLE_CHANGE", "Role change"),
                            ("STATUS_TRANSITION", "Status transition"),
                            ("RECORD_CREATED", "Record created"),
                            ("RECORD_UPDATED", "Record updated"),
                            ("RECORD_DELETED", "Record deleted"),
                        ],
                        max_length=40,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=80)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_log_entity__c2633a_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_log_actor_i_2ba9f4_idx",
                    ),
                ],
            },
        ),
    ]
