# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organization", "0001_initial"),
        ("plans", "0001_initial"),
        ("questionnaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiaCriticalContact",
            fields=[
                (
                    "critical_contact_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("contact_type", models.CharField(blank=True, max_length=80)),
                ("shift_timings", models.CharField(blank=True, max_length=100)),
                ("primary_phone", models.CharField(blank=True, max_length=50)),
                ("alternate_phone", models.CharField(blank=True, max_length=50)),
                ("seat_count", models.IntegerField(blank=True, null=True)),
                ("voice_non_voice", models.CharField(blank=True, max_length=30)),
                ("asset_id", models.CharField(blank=True, max_length=100)),
                ("asset_make", models.CharField(blank=True, max_length=150)),
                ("hardware_software", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="critical_contact_entries",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_contacts",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "bia_critical_contacts",
            },
        ),
        migrations.CreateModel(
            name="BiaServiceDescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_description_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("process_description", models.TextField(blank=True)),
                (
                    "mao",
                    models.CharField(blank=True, max_length=100, verbose_name="MAO"),
                ),
                (
                    "mbco",
                    models.CharField(blank=True, max_length=100, verbose_name="MBCO"),
                ),
                (
                    "rto",
                    models.CharField(blank=True, max_length=100, verbose_name="RTO"),
                ),
                (
                    "rpo",
                    models.CharField(blank=True, max_length=100, verbose_name="RPO"),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="cost_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_descriptions",
                        to="organization.costcode",
                    ),
                ),
                (
                    "owner_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_descriptions",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_descriptions",
                        to="plans.planversion",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        db_column="process_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_descriptions",
                        to="organization.process",
                    ),
                ),
                (
                    "subprocess",
                    models.ForeignKey(
                        blank=True,
                        db_column="subprocess_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_descriptions",
                        to="organization.subprocess",
                    ),
                ),
            ],
            options={
                "db_table": "bia_service_descriptions",
            },
        ),
        migrations.CreateModel(
            name="QuestionComment",
            fields=[
                (
                    "question_comment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_column="author_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_comments",
                        to="plans.planversion",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_column="question_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="questionnaire.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkRequirement",
            fields=[
                (
                    "network_requirement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("BIA_PROJECT", "BIA project"),
                            ("BCP_PLAN", "BCP plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_ip", models.CharField(blank=True, max_length=100)),
                ("destination_ip", models.CharField(blank=True, max_length=100)),
                ("port_number", models.CharField(blank=True, max_length=50)),
                ("connectivity_type", models.CharField(blank=True, max_length=100)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_requirements",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_requirements",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "network_requirements",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requirement_type__in", ["BIA_PROJECT", "BCP_PLAN"])
                        ),
                        name="ck_requirement_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("answer_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "answer_context",
                    models.CharField(
                        choices=[
                            ("BCP", "BCP"),
                            ("BIA", "BIA"),
                            ("INTERNAL_DEPENDENCY", "Internal dependency"),
                            ("EXTERNAL_DEPENDENCY", "External dependency"),
                            ("SUBCONTRACTOR", "Subcontractor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("answer_json", models.JSONField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="plans.planversion",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="questionnaire.question",
                    ),
                ),
                (
                    "respondent_user",
                    models.ForeignKey(
                        db_column="respondent_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_answers",
                "abstract": False,
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(fields=["question"], name="idx_answer_question")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "plan_version",
                            "question",
                            "respondent_user",
                            "answer_context",
                        ),
                        name="uq_question_answer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "answer_context__in",
                                [
                                    "BCP",
                                    "BIA",
                                    "INTERNAL_DEPENDENCY",
                                    "EXTERNAL_DEPENDENCY",
                                    "SUBCONTRACTOR",
                                ],
                            )
                        ),
                        name="ck_answer_context",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SectionStatus",
            fields=[
                (
                    "section_status_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="changed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_statuses",
                        to="plans.planversion",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="questionnaire.section",
                    ),
                ),
            ],
            options={
                "db_table": "section_statuses",
                "indexes": [
                    models.Index(
                        fields=["plan_version", "section"], name="idx_secstat_version"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_version", "section"), name="uq_section_status"
                    )
                ],
            },
        ),
    ]
