# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityDocument",
            fields=[
                (
                    "entity_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PLAN_VERSION", "Plan version"),
                            ("EXEMPTION", "Exemption"),
                            ("TEST", "Test"),
                            ("TEST_OUTCOME", "Test outcome"),
                            ("CRISIS_EVENT", "Crisis event"),
                            ("COST_CODE", "Cost code"),
                            ("HELP_RESOURCE", "Help resource"),
                        ],
                        max_length=80,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("document_type", models.CharField(blank=True, max_length=80)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "entity_documents",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_entdoc_entity"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "document",
                            "entity_type",
                            "entity_id",
                            "document_type",
                        ),
                        name="uq_entity_document",
                    )
                ],
            },
        ),
    ]
