# Generated by Django 5.2.17 on 2026-09-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("document_template_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_code", models.CharField(max_length=80)),
                ("version_number", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active_flag", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_templates",
                "ordering": ["template_code", "-version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template_code", "version_number"),
                        name="uq_document_template_version",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_column="document_template_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documenttemplate",
            ),
        ),
    ]
