# Generated by Django 5.2.17 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitydocument",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("PLAN_VERSION", "Plan version"),
                    ("EXEMPTION", "Exemption"),
                    ("TEST", "Test"),
                    ("TEST_OUTCOME", "Test outcome"),
                    ("CRISIS_EVENT", "Crisis event"),
                    ("COST_CODE", "Cost code"),
                    ("HELP_RESOURCE", "Help resource"),
                    ("REPORT_REQUEST", "Report request"),
                ],
                max_length=80,
            ),
        ),
    ]
