# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "help_resource_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_resources_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_resources",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "help_resources",
                "ordering": ["category", "display_order", "title"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
