# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("plan_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        db_column="cost_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="organization.costcode",
                    ),
                ),
                (
                    "owner_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_plans",
                        to="accounts.employee",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        db_column="process_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="organization.process",
                    ),
                ),
            ],
            options={
                "db_table": "plans",
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_version_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("version_number", models.IntegerField()),
                ("plan_mode", models.CharField(blank=True, max_length=50)),
                ("review_mode", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Work in Progress", "Work in Progress"),
                            ("Pending BU Lead Review", "Pending BU Lead Review"),
                            ("Approved", "Approved"),
                            ("Rework", "Rework"),
                            ("Exempted", "Exempted"),
                        ],
                        default="Not Started",
                        max_length=50,
                    ),
                ),
                ("published_flag", models.BooleanField(default=False)),
                ("copied_flag", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        db_column="plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="plans.plan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_versions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plan_versions",
                "ordering": ["plan", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="PlanStatusHistory",
            fields=[
                (
                    "plan_status_history_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Work in Progress", "Work in Progress"),
                            ("Pending BU Lead Review", "Pending BU Lead Review"),
                            ("Approved", "Approved"),
                            ("Rework", "Rework"),
                            ("Exempted", "Exempted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="changed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "plan_status_history",
                "ordering": ["plan_version", "changed_at"],
            },
        ),
        migrations.CreateModel(
            name="CoordinatorAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "coordinator_assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("coordinator_type", models.CharField(blank=True, max_length=80)),
                ("additional_user_flag", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinator_assignments",
                        to="accounts.employee",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        db_column="estate_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinator_assignments",
                        to="organization.estate",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_assignments",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "coordinator_assignments",
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("process", "cost_code"), name="uq_plan_process_cost_code"
            ),
        ),
        migrations.AddIndex(
            model_name="planversion",
            index=models.Index(
                fields=["status", "published_flag"], name="idx_pv_status_pub"
            ),
        ),
        migrations.AddIndex(
            model_name="planversion",
            index=models.Index(
                fields=["plan", "-version_number"], name="idx_pv_plan_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "version_number"), name="uq_plan_version_number"
            ),
        ),
        migrations.AddIndex(
            model_name="planstatushistory",
            index=models.Index(
                fields=["plan_version", "changed_at"], name="idx_psh_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="coordinatorassignment",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "employee", "coordinator_type"),
                name="uq_coordinator_assignment",
            ),
        ),
    ]
