# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("Call Tree Test", "Call Tree Test"),
                            ("Tabletop Exercise", "Tabletop Exercise"),
                            ("Full Simulation", "Full Simulation"),
                            ("Walkthrough", "Walkthrough"),
                        ],
                        max_length=100,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="initiated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "tests",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="TestOutcome",
            fields=[
                (
                    "test_outcome_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("conducted_date", models.DateField(blank=True, null=True)),
                ("conducted_time", models.TimeField(blank=True, null=True)),
                ("result", models.TextField(blank=True)),
                (
                    "final_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Passed", "Passed"),
                            ("Partial", "Partial"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "final_report_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="final_report_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_outcomes",
                        to="documents.document",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="testing.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_outcomes",
                "ordering": ["-conducted_date"],
            },
        ),
    ]
