# Generated by Django 5.2.17 on 2026-09-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calltree", "0002_phase8"),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="call_tree_run",
            field=models.ForeignKey(
                blank=True,
                db_column="call_tree_run_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="calltree.calltreerun",
            ),
        ),
    ]
