# Generated by Django 5.2.17 on 2026-09-14 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calltree", "0003_phase10_indexes"),
        ("documents", "0003_phase9"),
        ("plans", "0001_initial"),
        ("testing", "0002_phase8"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["scheduled_date", "status"], name="idx_tests_date_status"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["plan_version", "status"], name="idx_tests_version_status"),
        ),
        migrations.AddIndex(
            model_name="testoutcome",
            index=models.Index(fields=["test", "conducted_date"], name="idx_outcomes_test_date"),
        ),
    ]
