# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exemption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "exemption_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Rework", "Rework"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("answer_1", models.CharField(blank=True, max_length=500)),
                ("answer_2", models.CharField(blank=True, max_length=500)),
                ("answer_3", models.CharField(blank=True, max_length=500)),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemptions",
                        to="plans.planversion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exemptions_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exemptions",
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExemptionComment",
            fields=[
                (
                    "exemption_comment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Approval"),
                            ("REWORK", "Rework"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_column="author_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exemption_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exemption",
                    models.ForeignKey(
                        db_column="exemption_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="exemptions.exemption",
                    ),
                ),
            ],
            options={
                "db_table": "exemption_comments",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("comment_type__in", ["APPROVAL", "REWORK", "GENERAL"])
                        ),
                        name="ck_exemption_comment_type",
                    )
                ],
            },
        ),
    ]
