# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("section_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("section_name", models.CharField(max_length=200)),
                ("answer_status", models.CharField(blank=True, max_length=50)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        db_column="subcategory_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="lookups.lookupvalue",
                    ),
                ),
            ],
            options={
                "db_table": "sections",
                "ordering": ["display_order", "section_id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                ("question_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("question_code", models.CharField(blank=True, max_length=100)),
                ("question_text", models.TextField()),
                ("question_description", models.TextField(blank=True)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single choice"),
                            ("MULTI_CHOICE", "Multiple choice"),
                            ("TEXT", "Free text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("SUBFORM", "Sub-form"),
                        ],
                        default="TEXT",
                        max_length=50,
                    ),
                ),
                ("required_flag", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "depends_on_operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EQUALS", "Equals"),
                            ("NOT_EQUALS", "Not equals"),
                            ("IN", "In"),
                        ],
                        max_length=20,
                    ),
                ),
                ("depends_on_value", models.CharField(blank=True, max_length=255)),
                ("lookup_type", models.CharField(blank=True, max_length=50)),
                (
                    "depends_on_question",
                    models.ForeignKey(
                        blank=True,
                        db_column="depends_on_question_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_questions",
                        to="questionnaire.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="questionnaire.section",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["section", "display_order", "question_id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("option_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("option_code", models.CharField(max_length=80)),
                ("option_label", models.CharField(max_length=255)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("active_flag", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questionnaire.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
                "ordering": ["question", "display_order", "option_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "option_code"),
                        name="uq_question_option_code",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["section"], name="idx_question_section"),
        ),
    ]
