# Generated by Django 5.2.17 on 2026-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_section_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="evidence_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="evidence_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="evidence_when_value",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
