# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("calltree", "0001_initial"),
        ("organization", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisisEvent",
            fields=[
                (
                    "crisis_event_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "csd_ticket_number",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Table Top", "Table Top"),
                            ("Call tree", "Call tree"),
                            ("Full Simulation", "Full Simulation"),
                            ("Walkthrough", "Walkthrough"),
                            ("Live Incident", "Live Incident"),
                        ],
                        max_length=80,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("initiated_flag", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Initiated", "Initiated"),
                            ("In Progress", "In Progress"),
                            ("Closed", "Closed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Planned",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call_tree_run",
                    models.ForeignKey(
                        blank=True,
                        db_column="call_tree_run_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crisis_events",
                        to="calltree.calltreerun",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        db_column="cost_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crisis_events",
                        to="organization.costcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crisis_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="plan_version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crisis_events",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "crisis_events",
                "ordering": ["-event_date", "-event_time"],
            },
        ),
        migrations.CreateModel(
            name="CmscMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(db_index=True, default=True)),
                (
                    "cmsc_member_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("member_name", models.CharField(max_length=200)),
                ("member_email", models.EmailField(blank=True, max_length=320)),
                ("center", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("country_code", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                (
                    "reporting_manager_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "reporting_manager_email",
                    models.EmailField(blank=True, max_length=320),
                ),
                ("action_required_flag", models.BooleanField(default=False)),
                ("email_sent_status", models.CharField(blank=True, max_length=50)),
                ("bulk_call_status", models.CharField(blank=True, max_length=50)),
                ("bulk_call_status_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bu_lead",
                    models.ForeignKey(
                        blank=True,
                        db_column="bu_lead_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_members",
                        to="organization.bulead",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        db_column="cost_code_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cmsc_members",
                        to="organization.costcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_members_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_memberships",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="plan_version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_members",
                        to="plans.planversion",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        db_column="process_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_members",
                        to="organization.process",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmsc_members",
                        to="organization.region",
                    ),
                ),
            ],
            options={
                "db_table": "cmsc_members",
                "ordering": ["member_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(fields=["cost_code"], name="idx_cmsc_cost_code")
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
