# Generated by Django 5.2.17 on 2026-09-14 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calltree", "0003_phase10_indexes"),
        ("crisis", "0001_initial"),
        ("organization", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crisisevent",
            index=models.Index(fields=["cost_code", "created_at"], name="idx_crisis_cc_created"),
        ),
        migrations.AddIndex(
            model_name="crisisevent",
            index=models.Index(fields=["status", "event_type"], name="idx_crisis_status_type"),
        ),
    ]
