# Generated by Django 5.2.17 on 2026-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisis", "0002_phase10_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="crisisevent",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
