# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryStrategy",
            fields=[
                (
                    "recovery_strategy_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("core_strategy", models.TextField(blank=True)),
                ("tactical_strategy", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_strategies",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_strategies",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "recovery strategies",
                "db_table": "recovery_strategies",
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("risk_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("risk_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("impact_area", models.CharField(blank=True, max_length=150)),
                (
                    "likelihood_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "severity_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "control_effectiveness_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "inherent_risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "residual_risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("risk_level", models.CharField(blank=True, max_length=50)),
                ("target_closure_date", models.DateField(blank=True, null=True)),
                ("occurred_flag", models.BooleanField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to="accounts.employee",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        db_column="plan_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="plans.planversion",
                    ),
                ),
            ],
            options={
                "db_table": "risks",
                "ordering": ["-residual_risk_score", "risk_name"],
            },
        ),
        migrations.CreateModel(
            name="RiskAction",
            fields=[
                (
                    "risk_action_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("MITIGATION", "Mitigation"),
                            ("CONTINGENCY", "Contingency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "risk",
                    models.ForeignKey(
                        db_column="risk_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "db_table": "risk_actions",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("action_type__in", ["MITIGATION", "CONTINGENCY"])
                        ),
                        name="ck_risk_action_type",
                    )
                ],
            },
        ),
    ]
