# Generated by Django 5.2.17 on 2026-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="riskaction",
            index=models.Index(fields=["status", "target_date"], name="idx_actions_status_due"),
        ),
    ]
