# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookupCategory",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("category_name", models.CharField(max_length=200)),
                (
                    "category_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "lookup category",
                "verbose_name_plural": "lookup categories",
                "db_table": "question_categories",
                "ordering": ["category_type", "points", "category_name"],
            },
        ),
        migrations.CreateModel(
            name="LookupValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "legacy_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("subcategory_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="lookups.lookupcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "lookup value",
                "verbose_name_plural": "lookup values",
                "db_table": "question_subcategories",
                "ordering": ["subcategory_name"],
            },
        ),
    ]
