# Generated by Django 5.2.17 on 2026-09-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "notification_log_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PLAN_SUBMITTED", "Plan submitted for review"),
                            ("PLAN_APPROVED", "Plan approved"),
                            ("PLAN_REWORK", "Plan sent back for rework"),
                            ("COORDINATOR_ASSIGNED", "Coordinator assigned"),
                            ("EXEMPTION_SUBMITTED", "Exemption submitted"),
                            ("EXEMPTION_DECIDED", "Exemption approved or rejected"),
                            ("REVIEW_REMINDER", "Review pending reminder"),
                            ("RISK_ACTION_OVERDUE", "Risk action overdue"),
                            ("TEST_REMINDER", "Upcoming test reminder"),
                            ("OTP_CODE", "One-time passcode"),
                            ("PASSWORD_RESET", "Password reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=80)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("to_email", models.EmailField(max_length=320)),
                (
                    "cc_emails",
                    models.TextField(blank=True, help_text="Comma-separated."),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("template_name", models.CharField(blank=True, max_length=150)),
                ("context", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_detail", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="recipient_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_notif_entity"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="idx_notif_status"
                    ),
                ],
            },
        ),
    ]
