# Generated by Django 5.2.17 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_phase8"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PLAN_SUBMITTED", "Plan submitted for review"),
                    ("PLAN_APPROVED", "Plan approved"),
                    ("PLAN_REWORK", "Plan sent back for rework"),
                    ("COORDINATOR_ASSIGNED", "Coordinator assigned"),
                    ("EXEMPTION_SUBMITTED", "Exemption submitted"),
                    ("EXEMPTION_DECIDED", "Exemption approved or rejected"),
                    ("REVIEW_REMINDER", "Review pending reminder"),
                    ("RISK_ACTION_OVERDUE", "Risk action overdue"),
                    ("TEST_REMINDER", "Upcoming test reminder"),
                    ("CRISIS_INITIATED", "Crisis event initiated"),
                    ("CALL_TREE_NOTIFY", "Call tree email notification"),
                    ("CALL_TREE_ESCALATION", "Call tree escalation to BU lead"),
                    ("CALL_TREE_SUMMARY", "Call tree run summary"),
                    ("REPORT_READY", "Report ready"),
                    ("OTP_CODE", "One-time passcode"),
                    ("PASSWORD_RESET", "Password reset"),
                ],
                max_length=50,
            ),
        ),
    ]
