# Generated by Django 5.2.17 on 2026-09-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_phase9"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("push_subscription_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("endpoint", models.TextField()),
                ("endpoint_hash", models.CharField(max_length=64, unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("user_notification_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PLAN_SUBMITTED", "Plan submitted for review"),
                            ("PLAN_APPROVED", "Plan approved"),
                            ("PLAN_REWORK", "Plan sent back for rework"),
                            ("COORDINATOR_ASSIGNED", "Coordinator assigned"),
                            ("EXEMPTION_SUBMITTED", "Exemption submitted"),
                            ("EXEMPTION_DECIDED", "Exemption approved or rejected"),
                            ("REVIEW_REMINDER", "Review pending reminder"),
                            ("RISK_ACTION_OVERDUE", "Risk action overdue"),
                            ("TEST_REMINDER", "Upcoming test reminder"),
                            ("CRISIS_INITIATED", "Crisis event initiated"),
                            ("CALL_TREE_NOTIFY", "Call tree email notification"),
                            ("CALL_TREE_ESCALATION", "Call tree escalation to BU lead"),
                            ("CALL_TREE_SUMMARY", "Call tree run summary"),
                            ("REPORT_READY", "Report ready"),
                            ("OTP_CODE", "One-time passcode"),
                            ("PASSWORD_RESET", "Password reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.CharField(blank=True, max_length=1000)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_log",
                    models.ForeignKey(
                        blank=True,
                        db_column="notification_log_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_notifications",
                        to="notifications.notificationlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at", "created_at"], name="idx_usernotif_user_read"
                    )
                ],
            },
        ),
    ]
