# Generated by Django 5.2.17 on 2026-09-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_user_notifications_and_push"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotification",
            options={"ordering": ["-created_at", "-user_notification_id"]},
        ),
    ]
